[project]
name = "seoul-auction-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "koreanize-matplotlib>=0.1.1",
    "matplotlib>=3.10.8",
    "ngboost>=0.5.8",
    "pandas>=3.0.0",
    "shap>=0.49.1",
]
